from __future__ import annotations as annotations

import logging as logging
import re as re
from collections.abc import Callable, Iterable, Mapping, MutableMapping, MutableSequence, Sequence
from itertools import (
    accumulate as accumulate,
    batched as batched,
    chain as chain,
    combinations as combinations,
    combinations_with_replacement as combinations_with_replacement,
    compress as compress,
    count as count,
    cycle as cycle,
    dropwhile as dropwhile,
    filterfalse as filterfalse,
    groupby as groupby,
    islice as islice,
    pairwise as pairwise,
    permutations as permutations,
    product as product,
    repeat as repeat,
    starmap as starmap,
    takewhile as takewhile,
    tee as tee,
    zip_longest as zip_longest,
)
from typing import ClassVar, Generic, List as List, Optional as Optional, TypeVar, overload

_T = TypeVar("_T")
_DataT = TypeVar("_DataT")
_ValueT = TypeVar("_ValueT")

auto_id_field: str | None
NOT_SET: object
LIST_KEY: object
logger: logging.Logger

class JSONPath:
    def find(self, data: object) -> list[DatumInContext[object]]: ...
    def find_or_create(self, data: object) -> list[DatumInContext[object]]: ...
    def update(
        self,
        data: _DataT,
        val: _ValueT | Callable[[object, object, str | int], _ValueT | None],
    ) -> _DataT | _ValueT: ...
    def update_or_create(
        self,
        data: _DataT,
        val: _ValueT | Callable[[object, object, str | int], _ValueT | None],
    ) -> _DataT | _ValueT: ...
    def filter(self, fn: Callable[[object], bool], data: _DataT) -> _DataT | None: ...
    def child(self, child: JSONPath) -> JSONPath: ...
    def make_datum(self, value: _T | DatumInContext[_T]) -> DatumInContext[_T]: ...

class DatumInContext(Generic[_T]):
    path: JSONPath
    context: DatumInContext[object] | None
    @classmethod
    @overload
    def wrap(cls, data: DatumInContext[_T]) -> DatumInContext[_T]: ...
    @classmethod
    @overload
    def wrap(cls, data: _T) -> DatumInContext[_T]: ...
    def __init__(
        self,
        value: _T,
        path: JSONPath | None = None,
        context: object | None = None,
    ) -> None: ...
    @property
    def value(self) -> _T: ...
    @value.setter
    def value(self, value: _T) -> None: ...
    def in_context(self, context: object, path: JSONPath) -> DatumInContext[_T]: ...
    @property
    def full_path(self) -> JSONPath: ...
    @property
    def id_pseudopath(self) -> JSONPath: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class AutoIdForDatum(DatumInContext[str]):
    datum: DatumInContext[object]
    id_field: str | None
    def __init__(self, datum: DatumInContext[object], id_field: str | None = None) -> None: ...
    @property  # type: ignore[misc]
    def value(self) -> str: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @property
    def path(self) -> str | None: ...  # type: ignore[override]
    @property
    def context(self) -> DatumInContext[object]: ...  # type: ignore[override]
    def __repr__(self) -> str: ...
    def in_context(self, context: object, path: JSONPath) -> AutoIdForDatum: ...
    def __eq__(self, other: object) -> bool: ...

class Root(JSONPath):
    def find(self, data: _T | DatumInContext[_T]) -> list[DatumInContext[_T]]: ...
    def update(self, data: object, val: _ValueT) -> _ValueT: ...  # type: ignore[override]
    def filter(self, fn: Callable[[object], bool], data: _DataT) -> _DataT | None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class This(JSONPath):
    def find(self, datum: _T | DatumInContext[_T]) -> list[DatumInContext[_T]]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def update(self, data: object, val: _ValueT) -> _ValueT: ...  # type: ignore[override]
    def filter(self, fn: Callable[[object], bool], data: _DataT) -> _DataT | None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Child(JSONPath):
    left: JSONPath
    right: JSONPath
    def __init__(self, left: JSONPath, right: JSONPath) -> None: ...
    def find(self, datum: object) -> list[DatumInContext[object]]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def update(
        self,
        data: _DataT,
        val: _ValueT | Callable[[object, object, str | int], _ValueT | None],
    ) -> _DataT: ...
    def find_or_create(self, datum: object) -> list[DatumInContext[object]]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def update_or_create(
        self,
        data: _DataT,
        val: _ValueT | Callable[[object, object, str | int], _ValueT | None],
    ) -> _DataT: ...
    def filter(self, fn: Callable[[object], bool], data: _DataT) -> _DataT: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...

class Parent(JSONPath):
    def find(self, datum: object) -> list[DatumInContext[object] | None]: ...  # type: ignore[override]
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...

class Where(JSONPath):
    left: JSONPath
    right: JSONPath
    def __init__(self, left: JSONPath, right: JSONPath) -> None: ...
    def find(self, data: object) -> list[DatumInContext[object]]: ...
    def update(
        self,
        data: _DataT,
        val: _ValueT | Callable[[object, object, str | int], _ValueT | None],
    ) -> _DataT: ...
    def filter(self, fn: Callable[[object], bool], data: _DataT) -> _DataT: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class WhereNot(Where):
    def find(self, data: object) -> list[DatumInContext[object]]: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Descendants(JSONPath):
    left: JSONPath
    right: JSONPath
    def __init__(self, left: JSONPath, right: JSONPath) -> None: ...
    def find(self, datum: object) -> list[DatumInContext[object]]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def is_singular(self) -> bool: ...
    def update(
        self,
        data: _DataT,
        val: _ValueT | Callable[[object, object, str | int], _ValueT | None],
    ) -> _DataT: ...
    def filter(self, fn: Callable[[object], bool], data: _DataT) -> _DataT: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...

class Union(JSONPath):
    left: JSONPath
    right: JSONPath
    def __init__(self, left: JSONPath, right: JSONPath) -> None: ...
    def is_singular(self) -> bool: ...
    def find(self, data: object) -> list[DatumInContext[object]]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Intersect(JSONPath):
    left: JSONPath
    right: JSONPath
    def __init__(self, left: JSONPath, right: JSONPath) -> None: ...
    def is_singular(self) -> bool: ...
    def find(self, data: object) -> list[DatumInContext[object]]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Fields(JSONPath):
    fields: tuple[str, ...]
    def __init__(self, *fields: str) -> None: ...
    @staticmethod
    def get_field_datum(
        datum: DatumInContext[object], field: str, create: bool
    ) -> DatumInContext[object] | None: ...
    def reified_fields(self, datum: DatumInContext[object]) -> tuple[str, ...]: ...
    def find(self, datum: object) -> list[DatumInContext[object]]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def find_or_create(self, datum: object) -> list[DatumInContext[object]]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @overload
    def update(self, data: _DataT, val: Callable[[object, object, str], object]) -> _DataT: ...
    @overload
    def update(self, data: _DataT, val: object) -> _DataT: ...
    @overload
    def update_or_create(
        self, data: _DataT, val: Callable[[object, object, str], object]
    ) -> _DataT: ...
    @overload
    def update_or_create(self, data: _DataT, val: object) -> _DataT: ...
    def filter(self, fn: Callable[[object], bool], data: _DataT) -> _DataT: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Index(JSONPath):
    indices: tuple[int, ...]
    def __init__(self, *indices: int) -> None: ...
    def find(self, datum: object) -> list[DatumInContext[object]]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def find_or_create(self, datum: object) -> list[DatumInContext[object]]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def update(
        self,
        data: _DataT,
        val: _ValueT | Callable[[object, object, int], _ValueT | None],
    ) -> _DataT: ...
    def update_or_create(
        self,
        data: _DataT,
        val: _ValueT | Callable[[object, object, int], _ValueT | None],
    ) -> _DataT: ...
    def filter(self, fn: Callable[[object], bool], data: _DataT) -> _DataT: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...

class Slice(JSONPath):
    start: int | None
    end: int | None
    step: int | None
    def __init__(
        self, start: int | None = None, end: int | None = None, step: int | None = None
    ) -> None: ...
    def find(self, datum: object) -> list[DatumInContext[object]]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def update(
        self,
        data: _DataT,
        val: _ValueT | Callable[[object, object, int], _ValueT | None],
    ) -> _DataT: ...
    def filter(self, fn: Callable[[object], bool], data: _DataT) -> _DataT: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
