from __future__ import annotations

import logging as logging
import sys as sys
import types
from collections.abc import Iterator
from typing import ClassVar, Protocol

from .exceptions import JsonPathLexerError as JsonPathLexerError

jsonpath_ng: types.ModuleType
logger: logging.Logger

class _LexerState(Protocol):
    lineno: int
    lexpos: int
    latest_newline: int
    string_start: int
    string_value: str | None
    def push_state(self, state: str) -> None: ...
    def pop_state(self) -> None: ...

class _LexToken(Protocol):
    type: str
    value: str | int | float | bool
    lineno: int
    lexpos: int
    col: int
    lexer: _LexerState

class JsonPathLexer:
    debug: bool
    literals: ClassVar[list[str]]
    reserved_words: ClassVar[dict[str, str]]
    tokens: ClassVar[list[str]]
    states: ClassVar[list[tuple[str, str]]]
    t_DOUBLEDOT: ClassVar[str]
    t_ignore: ClassVar[str]
    t_singlequote_ignore: ClassVar[str]
    t_doublequote_ignore: ClassVar[str]
    t_backquote_ignore: ClassVar[str]
    def __init__(self, debug: bool = False) -> None: ...
    def tokenize(self, string: str) -> Iterator[_LexToken]: ...
    def t_ID(self, t: _LexToken) -> _LexToken: ...
    def t_NUMBER(self, t: _LexToken) -> _LexToken: ...
    def t_singlequote(self, t: _LexToken) -> None: ...
    def t_singlequote_content(self, t: _LexToken) -> None: ...
    def t_singlequote_escape(self, t: _LexToken) -> None: ...
    def t_singlequote_end(self, t: _LexToken) -> _LexToken: ...
    def t_singlequote_error(self, t: _LexToken) -> None: ...
    def t_doublequote(self, t: _LexToken) -> None: ...
    def t_doublequote_content(self, t: _LexToken) -> None: ...
    def t_doublequote_escape(self, t: _LexToken) -> None: ...
    def t_doublequote_end(self, t: _LexToken) -> _LexToken: ...
    def t_doublequote_error(self, t: _LexToken) -> None: ...
    def t_backquote(self, t: _LexToken) -> None: ...
    def t_backquote_escape(self, t: _LexToken) -> None: ...
    def t_backquote_content(self, t: _LexToken) -> None: ...
    def t_backquote_end(self, t: _LexToken) -> _LexToken: ...
    def t_backquote_error(self, t: _LexToken) -> None: ...
    def t_newline(self, t: _LexToken) -> None: ...
    def t_error(self, t: _LexToken) -> None: ...
