from __future__ import annotations

import logging as logging
import os as os
import sys as sys
from collections.abc import Callable, Iterable
from typing import ClassVar, Protocol

from . import _ply as jsonpath_ng
from .jsonpath import *
from .lexer import JsonPathLexer as JsonPathLexer, _LexToken
from .exceptions import JsonPathParserError as JsonPathParserError

logger: logging.Logger  # type: ignore[no-redef]

class _Production(Protocol):
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> object: ...
    def __setitem__(self, index: int, value: object) -> None: ...
    def lineno(self, index: int) -> int: ...
    def lexpos(self, index: int) -> int: ...

class _Parser(Protocol):
    def parse(self, *, lexer: IteratorToTokenStream) -> JSONPath: ...

def parse(string: str) -> JSONPath: ...

class JsonPathParser:
    tokens: ClassVar[list[str]]
    precedence: ClassVar[list[tuple[str, ...]]]
    debug: bool
    lexer_class: Callable[[], JsonPathLexer]
    parser: _Parser
    def __init__(
        self,
        debug: bool = False,
        lexer_class: Callable[[], JsonPathLexer] | None = None,
    ) -> None: ...
    def parse(self, string: str, lexer: JsonPathLexer | None = None) -> JSONPath: ...
    def parse_token_stream(self, token_iterator: Iterable[_LexToken]) -> JSONPath: ...
    def p_error(self, t: _LexToken | None) -> None: ...
    def p_jsonpath_binop(self, p: _Production) -> None: ...
    def p_jsonpath_fields(self, p: _Production) -> None: ...
    def p_jsonpath_named_operator(self, p: _Production) -> None: ...
    def p_jsonpath_root(self, p: _Production) -> None: ...
    def p_jsonpath_idx(self, p: _Production) -> None: ...
    def p_jsonpath_slice(self, p: _Production) -> None: ...
    def p_jsonpath_fieldbrackets(self, p: _Production) -> None: ...
    def p_jsonpath_child_fieldbrackets(self, p: _Production) -> None: ...
    def p_jsonpath_child_idxbrackets(self, p: _Production) -> None: ...
    def p_jsonpath_child_slicebrackets(self, p: _Production) -> None: ...
    def p_jsonpath_parens(self, p: _Production) -> None: ...
    def p_fields_or_any(self, p: _Production) -> None: ...
    def p_fields_id(self, p: _Production) -> None: ...
    def p_fields_comma(self, p: _Production) -> None: ...
    def p_idx(self, p: _Production) -> None: ...
    def p_idx_comma(self, p: _Production) -> None: ...
    def p_slice_any(self, p: _Production) -> None: ...
    def p_slice(self, p: _Production) -> None: ...
    def p_maybe_int(self, p: _Production) -> None: ...
    def p_empty(self, p: _Production) -> None: ...

class IteratorToTokenStream:
    iterator: Iterable[_LexToken]
    def __init__(self, iterator: Iterable[_LexToken]) -> None: ...
    def token(self) -> _LexToken | None: ...
