from __future__ import annotations

import logging as logging
import os as os
import sys as sys
import types
from collections.abc import Callable, Iterable
from typing import ClassVar, Protocol, TypeAlias, TypeVar, overload

from .jsonpath import *
from .ext.filter import Expression as _Expression
from .lexer import JsonPathLexer as JsonPathLexer, _LexToken
from .exceptions import JsonPathParserError as JsonPathParserError

jsonpath_ng: types.ModuleType

_ProductionValueT = TypeVar("_ProductionValueT")
_GrammarValue: TypeAlias = (
    JSONPath
    | str
    | int
    | float
    | bool
    | None
    | list[str]
    | list[int]
    | list[JSONPath]
    | list[_Expression]
    | tuple[JSONPath, bool]
    | list[tuple[JSONPath, bool]]
)

class _Production(Protocol[_ProductionValueT]):
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> _ProductionValueT: ...
    @overload
    def __getitem__(self, index: slice) -> list[_ProductionValueT]: ...
    def __setitem__(self, index: int, value: _ProductionValueT) -> None: ...
    def lineno(self, index: int) -> int: ...
    def lexpos(self, index: int) -> int: ...

class _Parser(Protocol):
    def parse(self, *, lexer: IteratorToTokenStream) -> JSONPath: ...

def parse(string: str) -> JSONPath: ...

class JsonPathParser:
    tokens: ClassVar[list[str]]
    precedence: ClassVar[list[tuple[str, ...]]]
    debug: bool
    lexer_class: Callable[[], JsonPathLexer]
    parser: _Parser
    def __init__(
        self,
        debug: bool = False,
        lexer_class: Callable[[], JsonPathLexer] | None = None,
    ) -> None: ...
    def parse(self, string: str, lexer: JsonPathLexer | None = None) -> JSONPath: ...
    def parse_token_stream(self, token_iterator: Iterable[_LexToken]) -> JSONPath: ...
    def p_error(self, t: _LexToken | None) -> None: ...
    def p_jsonpath_binop(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_fields(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_named_operator(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_root(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_idx(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_slice(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_fieldbrackets(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_child_fieldbrackets(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_child_idxbrackets(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_child_slicebrackets(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_parens(self, p: _Production[_GrammarValue]) -> None: ...
    def p_fields_or_any(self, p: _Production[_GrammarValue]) -> None: ...
    def p_fields_id(self, p: _Production[_GrammarValue]) -> None: ...
    def p_fields_comma(self, p: _Production[_GrammarValue]) -> None: ...
    def p_idx(self, p: _Production[_GrammarValue]) -> None: ...
    def p_idx_comma(self, p: _Production[_GrammarValue]) -> None: ...
    def p_slice_any(self, p: _Production[_GrammarValue]) -> None: ...
    def p_slice(self, p: _Production[_GrammarValue]) -> None: ...
    def p_maybe_int(self, p: _Production[_GrammarValue]) -> None: ...
    def p_empty(self, p: _Production[_GrammarValue]) -> None: ...

class IteratorToTokenStream:
    iterator: Iterable[_LexToken]
    def __init__(self, iterator: Iterable[_LexToken]) -> None: ...
    def token(self) -> _LexToken | None: ...
