from __future__ import annotations

import functools as functools
from collections.abc import Sequence

from ..jsonpath import DatumInContext as DatumInContext, JSONPath as JSONPath, This as This

class SortedThis(This):
    expressions: Sequence[tuple[JSONPath, bool]] | None
    def __init__(self, expressions: Sequence[tuple[JSONPath, bool]] | None = None) -> None: ...
    def find(self, datum: object) -> list[DatumInContext[object]]: ...  # type: ignore[override]
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Len(JSONPath):
    def find(self, datum: object) -> list[DatumInContext[int]]: ...  # type: ignore[override]
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Keys(JSONPath):
    def find(self, datum: object) -> list[DatumInContext[object]]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Path(JSONPath):
    def find(self, datum: object) -> list[DatumInContext[str]]: ...  # type: ignore[override]
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
