from __future__ import annotations

from typing import ClassVar

from .. import lexer as lexer, parser as parser
from ..jsonpath import Child as Child, Fields as Fields, JSONPath, This as This
from ..lexer import _LexToken
from ..parser import _GrammarValue, _Production

class ExtendedJsonPathLexer(lexer.JsonPathLexer):
    literals: ClassVar[list[str]]
    tokens: ClassVar[list[str]]
    t_FILTER_OP: ClassVar[str]
    def t_BOOL(self, t: _LexToken) -> _LexToken: ...
    def t_SORT_DIRECTION(self, t: _LexToken) -> _LexToken: ...
    def t_ID(self, t: _LexToken) -> _LexToken: ...
    def t_FLOAT(self, t: _LexToken) -> _LexToken: ...

class ExtendedJsonPathParser(parser.JsonPathParser):
    tokens: ClassVar[list[str]]
    precedence: ClassVar[list[tuple[str, ...]]]
    def __init__(
        self,
        debug: bool = False,
        lexer_class: type[lexer.JsonPathLexer] | None = None,
    ) -> None: ...
    def p_jsonpath_operator_jsonpath(self, p: _Production[_GrammarValue]) -> None: ...
    def p_operator(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_named_operator(self, p: _Production[_GrammarValue]) -> None: ...
    def p_expression(self, p: _Production[_GrammarValue]) -> None: ...
    def p_expressions_expression(self, p: _Production[_GrammarValue]) -> None: ...
    def p_expressions_and(self, p: _Production[_GrammarValue]) -> None: ...
    def p_expressions_parens(self, p: _Production[_GrammarValue]) -> None: ...
    def p_filter(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_filter(self, p: _Production[_GrammarValue]) -> None: ...
    def p_sort(self, p: _Production[_GrammarValue]) -> None: ...
    def p_sorts_sort(self, p: _Production[_GrammarValue]) -> None: ...
    def p_sorts_comma(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_sort(self, p: _Production[_GrammarValue]) -> None: ...
    def p_jsonpath_this(self, p: _Production[_GrammarValue]) -> None: ...

ExtentedJsonPathParser = ExtendedJsonPathParser

def parse(path: str, debug: bool = False) -> JSONPath: ...
