from __future__ import annotations

import re as re
from re import Pattern

from ..jsonpath import DatumInContext as DatumInContext, This as This

SUB: Pattern[str]
SPLIT: Pattern[str]
STR: Pattern[str]

class DefintionInvalid(Exception): ...

class Sub(This):
    expr: str
    repl: str
    regex: Pattern[str]
    method: str
    def __init__(self, method: str | None = None) -> None: ...
    def find(self, datum: object) -> list[DatumInContext[str]]: ...  # type: ignore[override]
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Split(This):
    chars: str
    segment: str
    max_split: int
    method: str
    def __init__(self, method: str | None = None) -> None: ...
    def find(self, datum: object) -> list[DatumInContext[str | list[str]]]: ...  # type: ignore[override]
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Str(This):
    method: str
    def __init__(self, method: str | None = None) -> None: ...
    def find(self, datum: object) -> list[DatumInContext[str]]: ...  # type: ignore[override]
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
